language: node_js #设置语言

node_js:
  - node
cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
before_install:
  - npm install -g pnpm

install:
  - pnpm install

script:
  - pnpm build

# E: Build LifeCycle

# 只有指定的分支提交时才会运行脚本
branches:
  - master
  - dev