language: node_js #设置语言

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-13.2

env:
  - CXX=g++-13.2

node_js:
  - node

os:
  - windows

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
before_install:
  - npm install -g pnpm

install:
  - pnpm install

script:
  - pnpm build

# E: Build LifeCycle

# 只有指定的分支提交时才会运行脚本
branches:
  - master
  - dev
